### ISSUE TITLE
Reminder to add metadata to code files

### ISSUE THREAD

**Issue by jglev** [greenelab/library-access#14]
I'm opening this issue as a reminder that, per the [Lab onboarding documentation checklist](http://greenelab-onboarding.readthedocs.io/en/latest/#code-review-checklist), we need to do the following at some point for code files:

1. Sign the files
2. Add a docstring to each of the files
3. For smaller functions, add a docstring

**Comment by dhimmel** [comment]
Regarding "signing the files", we use the git history to take care of that. For example, see [GitHub's blame](https://github.com/greenelab/library-access/blame/172622f8b2a2f04a9284927227da36ce7732e793/library_management_system_downloader/run_api_download_and_parse_results.py) for a file in this repo.

Regarding documentation, we do want to make things clearly documented. Usually, you want to write the doc as you make the files and functions. Sometimes code is clear and doesn't necessarily need docstrings. Are there specific areas of the code where documentation is lacking?

I think the main area where this repo is lacking documentation is in the README. We should update the README to better describe:

1. what the repository does
2. how to use, rerun, or modify it
3. the repository contents (directories and files)

As a reference, you can look at [`greenelab/crossref`](https://github.com/greenelab/crossref) to see how we might want to bolster the README.

**Comment by dhimmel** [comment]
@publicus sort of related to the above discussion, it would be good to add a note to the README letting users know how to rerun this analysis and to modify for another university.

**Comment by jglev** [comment]
@dhimmel Agreed! I can work on that, likely on Friday morning. Does that timing work for you?

**Comment by dhimmel** [comment]
> Agreed! I can work on that, likely on Friday morning. Does that timing work for you?

Sure this is not a time sensitive change although it'd be nice to get it done.

**Comment by dhimmel** [comment]
Closed by https://github.com/greenelab/library-access/pull/26
